server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mahuaapi
    username: root
    password: "123456"
    mail:
      # 配置 SMTP 服务器地址
      host: smtp.qq.com
      # 发送者邮箱
      username: XXXXXXXX@qq.com
      # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
      password: XXXXXXXXX
      # 端口号465或587
      port: 587
      # 默认的邮件编码为UTF-8
      default-encoding: UTF-8
      # 配置SSL 加密工厂
      properties: # 设置邮件超时时间防止服务器阻塞
        timeout: 5000
        connection-timeout: 5000
        write-timeout: 5000
        mail:
          smtp:
            socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

mahuaapi:
  client:
    access-key: mahua
    secret-key: 123456
dubbo:
  config-center:
    timeout: 40000
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.183.128:8848
