server:
  port: 8090

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8081/
          predicates:
            - Path=/api/service/{api_url}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
  file:
    path: logs

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.183.137:8848
